// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6RxzFbEt8bCQn4-435pFw-M-C9I-x8mE',
    appId: '1:1087948681654:web:b69718f23c44a61b2e1117',
    messagingSenderId: '1087948681654',
    projectId: 'iot-smoke-level',
    authDomain: 'iot-smoke-level.firebaseapp.com',
    databaseURL: 'https://iot-smoke-level-default-rtdb.firebaseio.com',
    storageBucket: 'iot-smoke-level.firebasestorage.app',
    measurementId: 'G-6CRBL1TBXW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8lrJ9aZ0lATxtb6tIDOm9LSXYJudbOcw',
    appId: '1:1087948681654:android:09c712d784bc0c1d2e1117',
    messagingSenderId: '1087948681654',
    projectId: 'iot-smoke-level',
    databaseURL: 'https://iot-smoke-level-default-rtdb.firebaseio.com',
    storageBucket: 'iot-smoke-level.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-s5VYn7a6GfCMCt2pyvoaLc1d2SP1WdI',
    appId: '1:1087948681654:ios:f6879074129613d52e1117',
    messagingSenderId: '1087948681654',
    projectId: 'iot-smoke-level',
    databaseURL: 'https://iot-smoke-level-default-rtdb.firebaseio.com',
    storageBucket: 'iot-smoke-level.firebasestorage.app',
    iosBundleId: 'com.example.iot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-s5VYn7a6GfCMCt2pyvoaLc1d2SP1WdI',
    appId: '1:1087948681654:ios:f6879074129613d52e1117',
    messagingSenderId: '1087948681654',
    projectId: 'iot-smoke-level',
    databaseURL: 'https://iot-smoke-level-default-rtdb.firebaseio.com',
    storageBucket: 'iot-smoke-level.firebasestorage.app',
    iosBundleId: 'com.example.iot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6RxzFbEt8bCQn4-435pFw-M-C9I-x8mE',
    appId: '1:1087948681654:web:15ac38a54e772e852e1117',
    messagingSenderId: '1087948681654',
    projectId: 'iot-smoke-level',
    authDomain: 'iot-smoke-level.firebaseapp.com',
    databaseURL: 'https://iot-smoke-level-default-rtdb.firebaseio.com',
    storageBucket: 'iot-smoke-level.firebasestorage.app',
    measurementId: 'G-SXGWS7B230',
  );
}
